baseURL = "https://examplesite.org"
copyright = ""
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disqusShortname = ""
enableEmoji = true
enableGitInfo = false
footnotereturnlinkcontents = "<sup>^</sup>"
googleAnalytics = ""
hasCJKLanguage = false
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10
removePathAccents = true
theme = "academia-hugo"
title = "Earl's Website"
[blackfriday]
angledQuotes = false
extensions = ["backslashLineBreak"]
hrefTargetBlank = true
latexDashes = true
[imaging]
anchor = "smart"
quality = 90
resampleFilter = "lanczos"
[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]
[taxonomies]
author = "authors"
category = "categories"
publication_type = "publication_types"
tag = "tags"
